github: colinodell
patreon: colinodell
tidelift: packagist/league%2fcommonmark
custom: ["https://www.colinodell.com/sponsor", "https://www.paypal.me/colinpodell/10.00", "https://enjoy.gitstore.app/repositories/thephpleague/commonmark"]
