use-sort:
    sort-type: alph

header: |
    /*
     * This is part of the webuni/commonmark-table-extension package.
     *
     * (c) Martin Hasoň <martin.hason@gmail.com>
     *
     * For the full copyright and license information, please view the LICENSE
     * file that was distributed with this source code.
     */

